name: Suggest a plugin
description: Suggest a folia compatible plugin
labels:
  - enhancement
assignees:
  - NonSwag
title: "Suggestion: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in this project and your time in submitting a suggestion!
        Fill out the following form to your best ability, and we'll get back to you as soon as possible.

  - type: input
    attributes:
      label: The name of the plugin
    validations:
      required: true

  - type: input
    attributes:
      label: Sourcecode URL
      description: GitHub, GitLab, Bitbucket, etc.
      placeholder: https://github.com/org/repo
    validations:
      required: true

  - type: input
    attributes:
      label: Download URL
      description: Modrinth, Hangar, CurseForge, SpigotMC, etc..
      placeholder: https://modrinth.com/project/example
    validations:
      required: true

  - type: input
    attributes:
      label: Description of the plugin
      description: A sentence or two describing the plugin
      placeholder: A plugin that does something really awesome

  - type: checkboxes
    attributes:
      label: Checklist
      description: Please answer truthfully to the following questions.
      options:
        - label: I am the author of the plugin.
        - label: The given URLs are valid and point to the plugin's actual sourcecode and download.
          required: true
        - label: The plugin is compatible with the latest version of Folia.
          required: true
